# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    filter_sets: 

        square_thumbnail_md: 
            filters: 
                thumbnail:
                    size: [300, 300]
                    mode: outbound
                    allow_upscale: true

        square_thumbnail_sm: 
            filters: 
                thumbnail:
                    size: [200, 200]
                    mode: outbound
                    allow_upscale: true
