vich_uploader:
    db_driver: orm

    mappings:
        pin_path:
            uri_prefix: /upload/pin
            upload_destination: '%kernel.project_dir%/public/upload/pin'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true